<?php
/**
 * @file
 * Reloads the current page if a user's session has ended, logging them out,
 * and ejecting them from the site.
 */

/**
 * Implements hook_menu().
 */
function ejectorseat_menu() {
  $items = array();

  $items['admin/config/people/ejectorseat'] = array(
    'title' => 'Ejector Seat settings',
    'description' => 'Configure Ejector Seat options.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('ejectorseat_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ejectorseat.admin.inc',
  );
  $items['ejectorseat/check'] = array(
    'page callback' => 'ejectorseat_check',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function ejectorseat_init() {
  global $user;
  if ($user->uid > 0 && (int) config_get('ejectorseat.settings', 'ejectorseat_interval')) {
    backdrop_add_js(array(
      'ejectorSeat' => array(
        'interval' => config_get('ejectorseat.settings', 'ejectorseat_interval'),
        'url' => url('ejectorseat/check'),
        'ignoreFocus' => config_get('ejectorseat.settings', 'ejectorseat_background') ? TRUE : FALSE,
      ),
    ), array('type' => 'setting', 'scope' => JS_DEFAULT));
    backdrop_add_js(backdrop_get_path('module', 'ejectorseat') . '/ejectorseat.js');
  }
}

/**
 * Callback to check whether a user is logged in or not.
 *
 * Intended to be the target of an AJAX request. This callback prints out the
 * integer 0 if the user accessing the site is anonymous and 1 if the user is
 * logged in.
 */
function ejectorseat_check() {
  global $user;
  print $user->uid == 0 ? 0 : 1;
}
